### ISSUE TITLE
games-arcade/stepmania fails to emerge

### ISSUE THREAD

**Issue by john5788** [gentoo-zh/overlay#342] opened 2015-11-08 00:02 UTC
I get an error trying to emerge stepmania:

```
>>> Failed to emerge games-arcade/stepmania-5.9999, Log file:

>>>  '/var/tmp/portage/games-arcade/stepmania-5.9999/temp/build.log'

 * Messages for package games-arcade/stepmania-5.9999:

 * Failed Patch: 11_all_fix-uninitialized-avframe.patch !
 *  ( /var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_fix-uninitialized-avframe.patch )
 * 
 * Include in your bugreport the contents of:
 * 
 *   /var/tmp/portage/games-arcade/stepmania-5.9999/temp/11_all_fix-uninitialized-avframe.patch.out
 * ERROR: games-arcade/stepmania-5.9999::gentoo-zh failed (prepare phase):
 *   Failed Patch: 11_all_fix-uninitialized-avframe.patch!
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 3716:  Called epatch
 *   environment, line 1948:  Called die
 * The specific snippet of code:
 *               die "Failed Patch: ${patchname}!";
 * 
 * If you need support, post the output of `emerge --info '=games-arcade/stepmania-5.9999::gentoo-zh'`,
 * the complete build log and the output of `emerge -pqv '=games-arcade/stepmania-5.9999::gentoo-zh'`.
 * The complete build log is located at '/var/tmp/portage/games-arcade/stepmania-5.9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-arcade/stepmania-5.9999/temp/environment'.
 * Working directory: '/var/tmp/portage/games-arcade/stepmania-5.9999/work/stepmania-5.9999'
 * S: '/var/tmp/portage/games-arcade/stepmania-5.9999/work/stepmania-5.9999'
```

```
# cat  /var/tmp/portage/games-arcade/stepmania-5.9999/temp/11_all_fix-uninitialized-avframe.patch.out
***** 11_all_fix-uninitialized-avframe.patch *****
PWD: /var/tmp/portage/games-arcade/stepmania-5.9999/work/stepmania-5.9999
PATCH TOOL: patch -> /usr/bin/patch
VERSION INFO:
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

==================================================

PATCH COMMAND:  patch -p0 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_fix-uninitialized-avframe.patch'

==================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 8afe1cf17c5d58182f010f540c49a2648f5c2f57 Mon Sep 17 00:00:00 2001
|From: Vincent Laviron <vincent.laviron@gmail.com>
|Date: Thu, 3 Apr 2014 17:28:13 +0200
|Subject: [PATCH] FFMpeg: Fix uninitialized AVFrame Fixes crashes with recent
| version of libav and ffmpeg on Linux while attempting to play a video
|
|---
| src/arch/MovieTexture/MovieTexture_FFMpeg.cpp | 11 ++++++-----
| src/arch/MovieTexture/MovieTexture_FFMpeg.h   |  2 +-
| 2 files changed, 7 insertions(+), 6 deletions(-)
|
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|index 51cfbd5..923e602 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.h b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|index 0c017d8..f4d25ef 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
==================================================

PATCH COMMAND:  patch -p1 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_fix-uninitialized-avframe.patch'

==================================================
checking file src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
Hunk #1 FAILED at 112.
Hunk #2 FAILED at 267.
Hunk #3 FAILED at 286.
Hunk #4 FAILED at 299.
Hunk #5 FAILED at 350.
5 out of 5 hunks FAILED
checking file src/arch/MovieTexture/MovieTexture_FFMpeg.h
Hunk #1 FAILED at 63.
1 out of 1 hunk FAILED

patch program exited with status 1
==================================================

PATCH COMMAND:  patch -p2 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_fix-uninitialized-avframe.patch'

==================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 8afe1cf17c5d58182f010f540c49a2648f5c2f57 Mon Sep 17 00:00:00 2001
|From: Vincent Laviron <vincent.laviron@gmail.com>
|Date: Thu, 3 Apr 2014 17:28:13 +0200
|Subject: [PATCH] FFMpeg: Fix uninitialized AVFrame Fixes crashes with recent
| version of libav and ffmpeg on Linux while attempting to play a video
|
|---
| src/arch/MovieTexture/MovieTexture_FFMpeg.cpp | 11 ++++++-----
| src/arch/MovieTexture/MovieTexture_FFMpeg.h   |  2 +-
| 2 files changed, 7 insertions(+), 6 deletions(-)
|
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|index 51cfbd5..923e602 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.h b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|index 0c017d8..f4d25ef 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
==================================================

PATCH COMMAND:  patch -p3 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_fix-uninitialized-avframe.patch'

==================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 8afe1cf17c5d58182f010f540c49a2648f5c2f57 Mon Sep 17 00:00:00 2001
|From: Vincent Laviron <vincent.laviron@gmail.com>
|Date: Thu, 3 Apr 2014 17:28:13 +0200
|Subject: [PATCH] FFMpeg: Fix uninitialized AVFrame Fixes crashes with recent
| version of libav and ffmpeg on Linux while attempting to play a video
|
|---
| src/arch/MovieTexture/MovieTexture_FFMpeg.cpp | 11 ++++++-----
| src/arch/MovieTexture/MovieTexture_FFMpeg.h   |  2 +-
| 2 files changed, 7 insertions(+), 6 deletions(-)
|
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|index 51cfbd5..923e602 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.h b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|index 0c017d8..f4d25ef 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
==================================================

PATCH COMMAND:  patch -p4 -g0 -E --no-backup-if-mismatch  < '/var/lib/layman/gentoo-zh/games-arcade/stepmania/files/11_all_fix-uninitialized-avframe.patch'

==================================================
can't find file to patch at input line 16
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 8afe1cf17c5d58182f010f540c49a2648f5c2f57 Mon Sep 17 00:00:00 2001
|From: Vincent Laviron <vincent.laviron@gmail.com>
|Date: Thu, 3 Apr 2014 17:28:13 +0200
|Subject: [PATCH] FFMpeg: Fix uninitialized AVFrame Fixes crashes with recent
| version of libav and ffmpeg on Linux while attempting to play a video
|
|---
| src/arch/MovieTexture/MovieTexture_FFMpeg.cpp | 11 ++++++-----
| src/arch/MovieTexture/MovieTexture_FFMpeg.h   |  2 +-
| 2 files changed, 7 insertions(+), 6 deletions(-)
|
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|index 51cfbd5..923e602 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
can't find file to patch at input line 67
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/arch/MovieTexture/MovieTexture_FFMpeg.h b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|index 0c017d8..f4d25ef 100644
|--- a/src/arch/MovieTexture/MovieTexture_FFMpeg.h
|+++ b/src/arch/MovieTexture/MovieTexture_FFMpeg.h
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

patch program exited with status 1
```

**Comment by biergaizi** [comment] 2015-11-08 04:59
Duplicate of #298.

**Closed as completed by biergaizi** 2015-11-08 04:59 UTC
